### ISSUE TITLE
TypeError on Hermes version 94

### ISSUE THREAD

**Issue by randshell** [P1sec/hermes-dec#10]
Logs:

```bash
[...]
Address 256941: Line 17179891934 - Column 38654917786 - Statement 445715
  Address 256946: Line 17179891934 - Column 38654917784 - Statement 445715
  Address 256946: Line 19327375581 - Column 38654917789 - Statement 445715
  Address 256926: Line 19327375581 - Column 42949885084 - Statement 445715
  Address 256940: Line 19327375581 - Column 42949885115 - Statement 445715
Traceback (most recent call last):
  File "/home/kali/.local/bin/hbc-file-parser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/share/pipx/venvs/hermes-dec/lib/python3.11/site-packages/hermes_dec/parsers/hbc_file_parser.py", line 915, in main
    print_debug_info(hbc_reader.sources_data_storage)
  File "/home/kali/.local/share/pipx/venvs/hermes-dec/lib/python3.11/site-packages/hermes_dec/parsers/debug_info_parser.py", line 64, in print_debug_info
    current_statement += statement_delta
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by p1-mmr** [comment]
Hello,

I pushed something in commit 7379e9e, should be better this way?

**Comment by marin-m** [comment]
With the latest version from Git?
If yes, can you please share your sample at labs at p1sec dot com?

**Comment by p1-mmr** [comment]
Ah I pushed this commit to the `main`, sorry. Thanks for noticing.
